[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour OVH - les variables sont dans .env.production
[context.production.environment]
  NODE_ENV = "production"